(define/contract (min-subarray nums p)
  (-> (listof exact-integer?) exact-integer? exact-integer?)
  (let* ((total (apply + nums))
         (need (modulo total p)))
    (if (= need 0)
        0
        (let ((mp (make-hash)))
          (hash-set! mp 0 -1)
          (define-values (res prefix i)
            (for/fold ((res (length nums)) (prefix 0) (i 0))
                      ((x nums))
              (set! prefix (modulo (+ prefix x) p))
              (define target (modulo (+ prefix (- need)) p))
              (when (hash-has-key? mp target)
                (set! res (min res (- i (hash-ref mp target)))))
              (hash-set! mp prefix i)
              (values res prefix (+ i 1))))
          (if (= res (length nums)) -1 res)))))